Feature | Ausbau Stufen Gradle Plugin
Seitenbau/Vorlage-Prozessmodellierung-Serviceportal pull request #1
Opened 2023-06-05 11:33 UTC by ExLeonem

### Description
- update documentation
  - switch from `projectStage` to `status`
  - add migration guide
- update config file to use new status

### How to test

#### Old plugin tasks still working

1. Try the following tasks with the old plugin version
   - `uploadFormularFiles`
   - `uploadProcessModelFiles`
   - Tasks should still work when using `projectStage`

#### Switch from `projectStage` to `status` working

1. Switch to newest Plugin Version
2. Execute tasks
   - `uploadFormularFiles`
   - `uploadProcessModelFiles`
   - Tasks should work with the new `status` attribute in default.config

### Deployment-Locations

Check other PR's in bitbucket for deployment locations

2023-06-06 07:21 UTC, mattbond requested changes

2023-06-06 07:21 UTC, mattbond commented on migration.md
> +**Wichtig:** Ab einem einem Zeitpunkt X, wird die Verwendung der Projektstufen vollständig ausgebaut
Perhaps use wording like "deprecated"

2023-06-06 07:21 UTC, mattbond commented on migration.md
> +| CERTIFIED                | FINAl  |
Typo FINAl  -> FINAL

2023-06-06 08:12 UTC, ExLeonem commented
Erst Mergen wenn die neuste Version des Plugins selbst ausgeliefert wurde.

2023-06-12 07:00 UTC, mattbond approved these changes

2023-06-12 07:07 UTC, mattbond commented
The version number of the plug-in in build.gradle needs to be updated one published.

2023-06-20 07:30 UTC, closed without merging